CREATE DATABASE IF NOT EXISTS miPrimerRepo
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE miPrimerRepo;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    dni VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
